blank_issues_enabled: false

  - name: Goost documentation repository
    url: https://github.com/GoostGD/goost-docs
    about: Please report issues with documentation on the Goost documentation repository, not here.
